language: node_js
node_js:
  - "lts/*"
notifications:
  email: false

# Default phases (can be overridden in jobs)
install: npm ci
script:
  - npm run lint
  - npm test

stages:
  - name: test
  - name: publish
    if: branch = master

jobs:
  include:
    - name: "Test on Linux"
      stage: test
      os: linux
    - name: "Test on OSX"
      stage: test
      os: osx
    - name: "Test on Windows"
      stage: test
      os: windows
    - name: "Publish to NPM"
      stage: publish
      os: linux
      script: npx semantic-release
