language: node_js
node_js:
  - "lts/*"
notifications:
  email: false

stages:
  - name: lint
  - name: test
  - name: publish
    if: branch = master AND type != pull_request

jobs:
  include:
    - name: "Check Linting"
      stage: lint
      os: linux
      script: npm run lint
    - name: "Test on Linux"
      stage: test
      os: linux
      script: npm test
    - name: "Test on OSX"
      stage: test
      os: osx
      script: npm test
    - name: "Test on Windows"
      stage: test
      os: windows
      script: npm test
    - name: "Publish to NPM"
      stage: publish
      os: linux
      script: npx semantic-release
